services:
  redis:
    image: redis:alpine
    restart: always

  pyapp:
    image: ghcr.io/isaia91/weather-pyapp:latest 
    build: .
    depends_on:
      - redis
    restart: always
    ports:
      - "80:80"
